# This is a basic workflow to help you get started with Actions

name: Build BFBC2 Hook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x86

      - name: Setup NASM
        uses: ilammy/setup-nasm@v1

      - name: Build Boost
        working-directory: ./external/boost
        shell: cmd
        run: bootstrap.bat && b2 install address-model=32 define=BOOST_USE_WINAPI_VERSION=0x0502 --prefix=../../third_party/boost --with-date_time --with-log --with-regex --with-system release

      - name: Build OpenSSL
        working-directory: ./external/openssl
        shell: cmd
        run: |
          mkdir ..\..\third_party\openssl
          pushd ..\..\third_party\openssl
          set BUILD_PATH=%CD%
          popd
          perl Configure VC-WIN32 --prefix=%BUILD_PATH% enable-ssl2 && ms\do_nasm && nmake -f ms\ntdll.mak && nmake -f ms\ntdll.mak test && nmake -f ms\ntdll.mak install
          
      - name: Build OpenSSL (New)
        working-directory: ./external/openssl_new
        shell: cmd
        run: |
          mkdir ..\..\third_party\openssl_new
          pushd ..\..\third_party\openssl_new
          set BUILD_PATH=%CD%
          popd
          perl Configure VC-WIN32 --prefix=%BUILD_PATH% && nmake && nmake test && nmake install

      - name: Build ZLIB
        working-directory: ./external/zlib
        shell: cmd
        run: |
          cmake -A Win32 -DCMAKE_INSTALL_PREFIX=..\..\third_party\zlib .
          msbuild INSTALL.vcxproj /p:Configuration=Release /p:Platform=Win32
      
      - name: Build cpprestsdk
        working-directory: ./external/cpprestsdk
        shell: cmd
        run: |
          mkdir ..\..\third_party\cpprestsdk\
          mkdir ..\..\third_party\cpprestsdk\lib
          mklink ..\..\third_party\cpprestsdk\lib\libcrypto.lib ..\..\openssl_new\lib\libcrypto.lib
          mklink ..\..\third_party\cpprestsdk\lib\libssl.lib ..\..\openssl_new\lib\libssl.lib
          pushd ..\..\third_party\zlib\lib
          set ZLIB_FILE_PATH=%CD%\zlib.lib
          popd
          cmake -A Win32 -DBOOST_ROOT=..\..\third_party\boost\ -DBoost_USE_STATIC_LIBS=ON -DOPENSSL_INCLUDE_DIR=..\..\third_party\openssl_new\include -DOPENSSL_LIBRARIES=..\..\third_party\openssl_new\lib -DZLIB_LIBRARY=%ZLIB_FILE_PATH% -DZLIB_INCLUDE_DIR=..\..\third_party\zlib\include -DCMAKE_INSTALL_PREFIX=..\..\third_party\cpprestsdk .
          msbuild INSTALL.vcxproj /p:Configuration=Release /p:Platform=Win32
      
      - name: Build Detours
        working-directory: ./external/detours
        run: |
          mkdir ..\..\third_party\detours
          mkdir ..\..\third_party\detours\include
          mkdir ..\..\third_party\detours\lib
          nmake
          xcopy include\* ..\..\third_party\detours\include\
          xcopy lib.X86\* ..\..\third_party\detours\lib\

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          queries: security-and-quality
          languages: "cpp"
          source-root: dinput8
      
      - name: Autobuild hook
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ReleaseBuild
          path: Release
      
      - name: Compress Release
        if: ${{ github.event_name == 'release' }}
        run: |
          Compress-Archive -Path .\Release\*.dll -DestinationPath BFBC2_Hook_Release.zip

      - name: Upload Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v1
        with:
          files: BFBC2_Hook_Release.zip
      